version: '3.1'
services:
  web: 
    image: nginx:latest
    ports:
      - "80:80"
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
      - ./app:/app
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app  
  mysql:
    image: mariadb:latest
    environment:
        MYSQL_ROOT_PASSWORD: 'P@55w0rd'  
    volumes:
        - ./mysqldata:/var/lib/mysql
    ports:
        - 127.0.0.1:3306:3306    
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      - PMA_ARBITRARY=1      
volumes:
    mysqldata: {}
